---
- name: Update apt repositie
  apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes

- name: Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections creates=/usr/lib/jvm/java-7-oracle

# Install Java
- name: Install dependencies
  apt: pkg=oracle-java7-installer state=present
